version: "3.3"

services:
  #Nginx container
  mynginx:
    image: nginx:stable-alpine
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - $HOME/recipes-project/src:/var/www/html
      - $HOME/recipes-project/nginx/default.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - myphp
      - mysql
    networks:
      - mynet

  # Mysql container
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    volumes:
      - $HOME/recipes-project/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: recipes
      MYSQL_USER: php
      MYSQL_PASSWORD: php
      MYSQL_ROOT_PASSWORD: recipesapp
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - mynet

  # PHP-FPM container
  myphp:
    image: php:7.4-fpm
    container_name: myphp
    ports:
      - "9000:9000"
    volumes:
      - $HOME/recipes-project/src:/var/www/html
    depends_on:
      - mysql
    build:
        context: $HOME/recipes-project/php
        dockerfile: Dockerfile
    networks:
      - mynet

  # phpMyAdmin container
  phpMyAdmin:
    image: phpmyadmin

    restart: unless-stopped

    ports:
      - "8082:80"

    environment:
      PMA_HOST: mysql

    networks:
      - mynet

volumes:
  database: {}

networks:
  mynet:
    driver: bridge