version: "3.3"

services:

  # Mysql container
  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: recipes
      MYSQL_USER: php
      MYSQL_PASSWORD: php
      MYSQL_ROOT_PASSWORD: recipesapp
    networks:
      - mynet

  # PHP-FPM container
  myphp:
    image: php:7.4-fpm
    container_name: myphp
    ports:
      - "9000:9000"
    volumes:
      - $HOME/:/var/www/html
    depends_on:
      - mysql
    build:
        context: $HOME/recipesapp/php
        dockerfile: Dockerfile
    networks:
      - mynet
      
  #Nginx container
  mynginx:
    image: nginx:stable-alpine
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - $HOME/:/var/www/html
      - $HOME/recipesapp/nginx/nginx.ini:/etc/nginx/conf.d/default.conf
    depends_on:
      - myphp
    networks:
      - mynet

  # phpMyAdmin container
  phpMyAdmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
    networks:
      - mynet

volumes:
  database: {}

networks:
  mynet:
    driver: bridge
